'use strict';
class NavalConnection{
  constructor(onState,onChange){this.onState=onState;this.onChange=onChange;this.socket=null;this.session=null;this.state=null;this.connected=false;this.active=false;this.pending=false;this.message='';this.retry=0;}
  endpoint(){try{const configured=window.KICK_GO_SERVER;if(!configured&&(location.hostname.endsWith('.github.io')||location.protocol==='file:'||location.hostname==='game.local'))return null;const url=new URL(configured||location.origin);if(!['https:','http:'].includes(url.protocol)||(location.protocol==='https:'&&url.protocol!=='https:'))return null;url.protocol=url.protocol==='https:'?'wss:':'ws:';url.pathname='/ws/naval';url.hash='';url.search='';return url.href;}catch{return null;}}
  store(value){try{if(value)sessionStorage.setItem('naval-session:v1',JSON.stringify(value));else sessionStorage.removeItem('naval-session:v1');}catch{}}
  saved(){try{const s=JSON.parse(sessionStorage.getItem('naval-session:v1'));return s?.endpoint===this.endpoint()&&typeof s.code==='string'&&(s.role==='spectator'||typeof s.token==='string')?s:null;}catch{return null;}}
  change(message){if(message!==undefined)this.message=message;this.onChange();}
  begin(type,code,nickname){this.stop();this.store(null);this.session=null;this.state=null;this.action={type,code,nickname};this.retry=0;if(!this.endpoint()){this.change('온라인 서버 주소가 필요합니다. 배포된 게임 주소로 접속해 주세요.');return;}this.active=true;this.connect();}
  restore(session){this.stop();this.session=session;this.state=null;this.active=true;this.retry=0;this.connect();}
  connect(){if(!this.active)return;clearTimeout(this.timer);clearTimeout(this.timeout);this.connected=false;this.change(this.retry?'연결이 끊겨 같은 방에 재접속 중…':'대전 서버 연결 중… 처음 접속은 잠시 걸릴 수 있어요.');const ws=new WebSocket(this.endpoint());this.socket=ws;this.timeout=setTimeout(()=>{if(this.socket===ws&&!this.connected)ws.close();},20000);
    ws.onopen=()=>{if(ws!==this.socket)return;const action=this.session?(this.session.role==='spectator'?{type:'watch',code:this.session.code}:{type:'resume',code:this.session.code,token:this.session.token}):this.action;ws.send(JSON.stringify({version:1,...action}));};
    ws.onmessage=e=>{if(ws!==this.socket)return;let m;try{m=JSON.parse(e.data);}catch{return;}
      if(m.type==='joined'){clearTimeout(this.timeout);this.retry=0;this.connected=true;this.pending=false;this.session={endpoint:this.endpoint(),code:m.code,token:m.token,team:m.team,role:m.role};this.store(this.session);this.change('');}
      else if(m.type==='state'){if(m.version!==1||m.code!==this.session?.code)return;this.state=m;this.pending=false;clearTimeout(this.requestTimer);this.message='';this.onState(m);}
      else if(m.type==='error'){this.pending=false;clearTimeout(this.requestTimer);const errors={ROOM_NOT_FOUND:'방이 없거나 만료됐습니다.',ROOM_FULL:'두 함장이 입장했습니다. 관전으로 들어갈 수 있습니다.',SPECTATORS_FULL:'관전 인원이 가득 찼습니다.',INVALID_SESSION:'이전 자리를 복구할 수 없습니다. 새 방을 만들어 주세요.',INVALID_FLEET:'함선 5척을 겹치지 않게 해역 안에 배치하세요.',PLACEMENT_LOCKED:'이미 배치를 확정했습니다.',STALE_STATE:'최신 상태로 갱신했습니다. 다시 선택해 주세요.',NOT_YOUR_TURN:'상대 차례입니다.',ALREADY_SHOT:'이미 공격한 좌표입니다.',OPPONENT_OFFLINE:'상대가 재접속하면 계속할 수 있습니다.',REMATCH_UNAVAILABLE:'경기 종료 후 두 함장이 연결되어야 재대결할 수 있습니다.',VERSION_MISMATCH:'새로고침해 최신 버전으로 접속하세요.',READ_ONLY:'관전자는 공격하거나 배치할 수 없습니다.',SERVER_FULL:'방이 가득 찼습니다. 잠시 후 다시 시도하세요.'};if(!this.connected||['ROOM_NOT_FOUND','INVALID_SESSION','VERSION_MISMATCH'].includes(m.code)){this.stop();this.session=null;this.state=null;this.store(null);}this.change(errors[m.code]||'요청을 처리하지 못했습니다. 다시 시도해 주세요.');}
      else if(m.type==='ended'){this.stop();this.session=null;this.state=null;this.store(null);this.change(m.reason==='REPLACED'?'다른 창에서 접속하여 이 창의 연결이 종료됐습니다.':m.reason==='EXPIRED'?'방이 만료됐습니다.':'방에서 나왔거나 함장이 퇴장하여 경기가 종료됐습니다.');}
    };
    ws.onerror=()=>{};ws.onclose=()=>{if(ws!==this.socket||!this.active)return;clearTimeout(this.timeout);clearTimeout(this.requestTimer);this.connected=false;this.pending=false;if(++this.retry>8){this.active=false;this.change('연결하지 못했습니다. 네트워크를 확인하고 재접속을 누르세요.');return;}this.change('재접속 중 · 배치와 공격은 잠시 잠깁니다.');this.timer=setTimeout(()=>this.connect(),Math.min(1000*2**(this.retry-1),10000));};
  }
  send(type,data={}){if(!this.connected||this.socket?.readyState!==1||this.pending)return false;this.pending=true;this.socket.send(JSON.stringify({version:1,type,match:this.state?.match,revision:this.state?.revision,...data}));this.requestTimer=setTimeout(()=>{if(this.socket?.readyState===1)this.socket.close();},10000);this.change('');return true;}
  leave(){if(this.socket?.readyState===1)this.socket.send(JSON.stringify({version:1,type:'leave'}));this.stop();this.session=null;this.state=null;this.store(null);this.change('로비로 돌아왔습니다.');}
  stop(){this.active=false;this.connected=false;this.pending=false;clearTimeout(this.timer);clearTimeout(this.timeout);clearTimeout(this.requestTimer);const ws=this.socket;this.socket=null;if(ws)ws.close();}
}
window.NavalConnection=NavalConnection;
